/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package myproject.budget_app;

import java.sql.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import myproject.Connect_DB.Operations;

/**
 *
 * @author jomsa
 */
public class Add extends javax.swing.JDialog {

    /**
     * Creates new form Add
     */
    public Add(java.awt.Frame parent, boolean modal, int uid) {
        super(parent, modal);
        setResizable(false);
        initComponents();
        this.uid = uid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        type_lbl = new javax.swing.JLabel();
        type_comboBx = new javax.swing.JComboBox<>();
        desc_lbl = new javax.swing.JLabel();
        cat_combobx = new javax.swing.JComboBox<>();
        add_trans_lbl = new javax.swing.JLabel();
        cat_lbl = new javax.swing.JLabel();
        desc_txt = new javax.swing.JTextField();
        amnt_lbl = new javax.swing.JLabel();
        amnt_txt = new javax.swing.JTextField();
        clear_bttn = new javax.swing.JButton();
        add_bttn = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        type_lbl.setBackground(new java.awt.Color(153, 153, 153));
        type_lbl.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        type_lbl.setText("Type");
        getContentPane().add(type_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, 30));

        type_comboBx.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        type_comboBx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an option:", "Expenses", "Income" }));
        getContentPane().add(type_comboBx, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, 30));

        desc_lbl.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        desc_lbl.setText("Description:");
        getContentPane().add(desc_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, 30));

        cat_combobx.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        cat_combobx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an option:", "Food", "Utilities", "Rent", "Transportation", "Health", "Shopping", "School Fees" }));
        getContentPane().add(cat_combobx, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 30));

        add_trans_lbl.setFont(new java.awt.Font("Poppins Black", 1, 18)); // NOI18N
        add_trans_lbl.setText("Add Transaction");
        getContentPane().add(add_trans_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 30));

        cat_lbl.setBackground(new java.awt.Color(153, 153, 153));
        cat_lbl.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        cat_lbl.setText("Category:");
        getContentPane().add(cat_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 30));

        desc_txt.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        getContentPane().add(desc_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 230, 30));

        amnt_lbl.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        amnt_lbl.setText("Amount:");
        getContentPane().add(amnt_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 70, 30));

        amnt_txt.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        getContentPane().add(amnt_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 170, 30));

        clear_bttn.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\clear_bttn.png")); // NOI18N
        clear_bttn.setBorderPainted(false);
        clear_bttn.setOpaque(false);
        clear_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clear_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clear_bttnMouseExited(evt);
            }
        });
        clear_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_bttnActionPerformed(evt);
            }
        });
        getContentPane().add(clear_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 50, 30));

        add_bttn.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\add_bttn.png")); // NOI18N
        add_bttn.setToolTipText("");
        add_bttn.setBorderPainted(false);
        add_bttn.setOpaque(false);
        add_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_bttnMouseExited(evt);
            }
        });
        add_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_bttnActionPerformed(evt);
            }
        });
        getContentPane().add(add_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 100, 40));

        bg.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\bg9.jpg")); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -180, 410, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clear_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_bttnActionPerformed
        // TODO add your handling code here:
        // Prompt the user for confirmation before clearing
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to clear all fields?", 
            "Confirm Clear", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);

        // If the user confirms, clear the fields
        if (confirm == JOptionPane.YES_OPTION) {
            clear(); // Call the clear method to reset fields
        }
    }//GEN-LAST:event_clear_bttnActionPerformed

    private void add_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_bttnMouseEntered
        // TODO add your handling code here:
        add_bttn.setIcon(new ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\add_bttn_clicked.png"));
    }//GEN-LAST:event_add_bttnMouseEntered

    private void add_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_bttnMouseExited
        // TODO add your handling code here:
        add_bttn.setIcon(new ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\add_bttn.png"));
    }//GEN-LAST:event_add_bttnMouseExited

    private void clear_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_bttnMouseEntered
        // TODO add your handling code here:
        clear_bttn.setIcon(new ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\clear_bttn_clicked.png"));
    }//GEN-LAST:event_clear_bttnMouseEntered

    private void clear_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_bttnMouseExited
        // TODO add your handling code here:
        clear_bttn.setIcon(new ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\clear_bttn.png"));
    }//GEN-LAST:event_clear_bttnMouseExited

    private void add_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_bttnActionPerformed
        // TODO add your handling code here:
        String category = getCategory();
        if (category == null) return;
        
        String type = collectType();
        if (type == null) return;
        
        String desc = getDesc();
        if (desc == null) return;
        
        int amount = getAmount();
        if (amount == -1) return;
        
        Date current = getCurrDate();
        
        Operations add = new Operations();
        add.addTrans(uid, desc, type, category, amount, current);
    }//GEN-LAST:event_add_bttnActionPerformed

    private String getCategory() {
        String selectedCat = cat_combobx.getSelectedItem().toString().trim();

        // Validate that a valid option is selected
        if (selectedCat.equals("Select an option:")) {
            JOptionPane.showMessageDialog(null, "Please select a valid category.");
            return null;  // Return null to indicate invalid selection
        }
        return selectedCat;  // Return the valid category
    }

    
    private String collectType() {
        String selectedType = type_comboBx.getSelectedItem().toString().trim();

        // Validate that a valid option is selected
        if (selectedType.equals("Select an option:")) {
            JOptionPane.showMessageDialog(null, "Please select a valid type.");
            return null;  // Return null to indicate invalid selection
        }
        return selectedType;  // Return the valid type
    }

    private java.sql.Date getCurrDate() {
        // Returns the current date without time
        return new java.sql.Date(System.currentTimeMillis());
    }

    private String getDesc() {
        String desc = desc_txt.getText().trim();  // Get and trim text from JTextField

        // Validate that the description is not empty
        if (desc.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Description cannot be empty. Please fill in the description.");
            return null;  // Return null to indicate invalid input
        }
        return desc;  // Return the valid description
    }

    private int getAmount() {
        String amountText = amnt_txt.getText().trim();  // Get the text and trim whitespace

        try {
            int amount = Integer.parseInt(amountText);  // Attempt to parse it as an integer

            // Validate that the amount is positive
            if (amount <= 0) {
                JOptionPane.showMessageDialog(null, "Please enter a positive number for the amount.");
                return -1;  // Return -1 to indicate invalid input
            }
            return amount;  // Return the valid amount
        } catch (NumberFormatException e) {
            // Handle cases where the input is not a valid number
            JOptionPane.showMessageDialog(null, "Please enter a valid number for the amount.");
            return -1;  // Return -1 to indicate invalid input
        }
    }

    private void clear() {
        // Clear the description text field if it's not null
        if (desc_txt != null) {
            desc_txt.setText(""); // Clear the description text field
        }

        // Clear the amount text field if it's not null
        if (amnt_txt != null) {
            amnt_txt.setText(""); // Clear the amount text field
        }

        // Reset combo boxes to their first choice (index 0)
        type_comboBx.setSelectedIndex(0); // Set type combo box to the first item
        cat_combobx.setSelectedIndex(0); // Set category combo box to the first item
    }
        
    
    /**
     * @param args the command line arguments
     */
    int uid;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_bttn;
    private javax.swing.JLabel add_trans_lbl;
    private javax.swing.JLabel amnt_lbl;
    private javax.swing.JTextField amnt_txt;
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox<String> cat_combobx;
    private javax.swing.JLabel cat_lbl;
    private javax.swing.JButton clear_bttn;
    private javax.swing.JLabel desc_lbl;
    private javax.swing.JTextField desc_txt;
    private javax.swing.JComboBox<String> type_comboBx;
    private javax.swing.JLabel type_lbl;
    // End of variables declaration//GEN-END:variables
}
