/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package myproject.budget_app;

import javax.swing.*;
import myproject.Connect_DB.AMS;
/**
 *
 * @author jomsa
 */
public class Log_in extends javax.swing.JDialog {

    /**
     * Creates new form Log_in
     */
    public Log_in(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
    }

    public Log_in(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setResizable(false);
        initComponents();
        setResizable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logBttn = new javax.swing.JButton();
        passTxt = new javax.swing.JPasswordField();
        haveAccLbl = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        SignInTransBttn = new javax.swing.JButton();
        welcomeLbl1 = new javax.swing.JLabel();
        createAccNowLbl = new javax.swing.JLabel();
        email_lbl = new javax.swing.JLabel();
        passLbl = new javax.swing.JLabel();
        seePassChkBx = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logBttn.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\Log_in.png")); // NOI18N
        logBttn.setBorderPainted(false);
        logBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logBttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logBttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logBttnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logBttnMouseReleased(evt);
            }
        });
        logBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBttnActionPerformed(evt);
            }
        });
        getContentPane().add(logBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 120, 50));

        passTxt.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        passTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTxtActionPerformed(evt);
            }
        });
        getContentPane().add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 300, 30));

        haveAccLbl.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        haveAccLbl.setForeground(new java.awt.Color(153, 153, 153));
        haveAccLbl.setText("Don't have an account?");
        getContentPane().add(haveAccLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, 30));

        email_txt.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });
        getContentPane().add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 300, 30));

        SignInTransBttn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        SignInTransBttn.setForeground(new java.awt.Color(0, 153, 204));
        SignInTransBttn.setText("Sign in");
        SignInTransBttn.setBorderPainted(false);
        SignInTransBttn.setOpaque(false);
        SignInTransBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInTransBttnActionPerformed(evt);
            }
        });
        getContentPane().add(SignInTransBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 80, -1));

        welcomeLbl1.setFont(new java.awt.Font("Poppins Black", 1, 24)); // NOI18N
        welcomeLbl1.setText("Welcome back");
        getContentPane().add(welcomeLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 210, 50));

        createAccNowLbl.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        createAccNowLbl.setForeground(new java.awt.Color(153, 153, 153));
        createAccNowLbl.setText("Log in to your account now");
        getContentPane().add(createAccNowLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 170, 30));

        email_lbl.setBackground(new java.awt.Color(0, 0, 0));
        email_lbl.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        email_lbl.setText("Email:");
        getContentPane().add(email_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, 30));

        passLbl.setBackground(new java.awt.Color(0, 0, 0));
        passLbl.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        passLbl.setText("Password:");
        getContentPane().add(passLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 80, 30));

        seePassChkBx.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        seePassChkBx.setForeground(new java.awt.Color(51, 51, 51));
        seePassChkBx.setText("See Password");
        seePassChkBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePassChkBxActionPerformed(evt);
            }
        });
        getContentPane().add(seePassChkBx, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\logInBg.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 620, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void seePassChkBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePassChkBxActionPerformed
        // TODO add your handling code here:
        // Toggle password visibility
        if (seePassChkBx.isSelected()) {
            passTxt.setEchoChar((char) 0); // Show password
        } else {
            passTxt.setEchoChar('*'); // Hide password
        }
    }//GEN-LAST:event_seePassChkBxActionPerformed

    private void logBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBttnActionPerformed
        // TODO add your handling code here:
        // Gather input fields
        JTextField[] inputFields = {email_txt, passTxt};

        // Validate input and retrieve values
        String[] validatedInput = validateInput(inputFields);
        if (validatedInput == null) {
            return; // Exit if validation fails
        }

        // Extract validated input
        String email = validatedInput[0];
        String password = validatedInput[1];

        // Attempt to log in the user
        AMS loginService = new AMS();
        boolean isLoginSuccessful = loginService.LogIn(email, password);

        if (isLoginSuccessful) {
            // Proceed to the main application only if login is successful
            Main mainMenu = new Main(email);
            this.dispose(); // Close the current dialog
            mainMenu.setVisible(true); // Show the main menu
        }
    }//GEN-LAST:event_logBttnActionPerformed

    private void passTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTxtActionPerformed

    private void SignInTransBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInTransBttnActionPerformed
        // TODO add your handling code here:
        clear();
        Sign_in sign = new Sign_in(this, true);
        this.dispose();
        sign.setVisible(true);
    }//GEN-LAST:event_SignInTransBttnActionPerformed

    private void logBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logBttnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logBttnMouseClicked

    private void logBttnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logBttnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_logBttnMouseReleased

    private void logBttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logBttnMouseEntered
        // TODO add your handling code here:
        //change
        logBttn.setIcon(new ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\Log_in_clicked.png"));
    }//GEN-LAST:event_logBttnMouseEntered

    private void logBttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logBttnMouseExited
        // TODO add your handling code here:
        logBttn.setIcon(new ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\Log_in.png"));
    }//GEN-LAST:event_logBttnMouseExited

    private String[] validateInput(JTextField[] field) {
        String[] input = new String[field.length];
        for (int i = 0; i < field.length; i++) {
            String text = field[i].getText().trim();
            if (text.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill all the fields.");
                return null; // Validation failed
            }          
            input[i] = text; // Assign text directly without concatenating
        }
        return input;
    }
    
    private void clear(){
        JTextField[] text = {email_txt, passTxt};
        for(int i = 0; i < text.length; i++){
            text[i].setText("");
        }
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignInTransBttn;
    private javax.swing.JLabel createAccNowLbl;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JTextField email_txt;
    private javax.swing.JLabel haveAccLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logBttn;
    private javax.swing.JLabel passLbl;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JCheckBox seePassChkBx;
    private javax.swing.JLabel welcomeLbl1;
    // End of variables declaration//GEN-END:variables
}
