/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myproject.budget_app;

import javax.swing.ImageIcon;

/**
 *
 * @author jomsa
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        log_bttn = new javax.swing.JButton();
        sign_bttn = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        illustration = new javax.swing.JLabel();
        header1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 100, 0, 0));

        jPanel1.setBackground(new java.awt.Color(108, 186, 34));
        jPanel1.setLayout(null);

        log_bttn.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\men_log.png")); // NOI18N
        log_bttn.setBorderPainted(false);
        log_bttn.setContentAreaFilled(false);
        log_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                log_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                log_bttnMouseExited(evt);
            }
        });
        log_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_bttnActionPerformed(evt);
            }
        });
        jPanel1.add(log_bttn);
        log_bttn.setBounds(610, 10, 80, 30);

        sign_bttn.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\men_sign.png")); // NOI18N
        sign_bttn.setBorderPainted(false);
        sign_bttn.setContentAreaFilled(false);
        sign_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sign_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sign_bttnMouseExited(evt);
            }
        });
        sign_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_bttnActionPerformed(evt);
            }
        });
        jPanel1.add(sign_bttn);
        sign_bttn.setBounds(700, 10, 80, 30);

        title.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\newTitle.png")); // NOI18N
        jPanel1.add(title);
        title.setBounds(-10, 0, 460, 50);

        illustration.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\illustration.png")); // NOI18N

        header1.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\header.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jLabel2.setText("What would you like to do next?");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel3.setText("Think of something you want to review");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel4.setText("like “view recent transactions” or ");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel5.setText("“check spending by category” ");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel6.setText("and see how we can help you stay ");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel7.setText("on top of your finances.");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(illustration, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(header1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(126, 126, 126))
                    .addComponent(illustration)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void log_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_bttnActionPerformed
        // TODO add your handling code here:
        Log_in log = new Log_in(this, true);
        this.dispose();
        log.setVisible(true);
    }//GEN-LAST:event_log_bttnActionPerformed

    private void sign_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_bttnActionPerformed
        // TODO add your handling code here:
        Sign_in sign = new Sign_in(this, true);
        this.dispose();
        sign.setVisible(true);
    }//GEN-LAST:event_sign_bttnActionPerformed

    private void sign_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_bttnMouseEntered
        // TODO add your handling code here:
        sign_bttn.setIcon(new ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\men_sign_clicked.png"));
    }//GEN-LAST:event_sign_bttnMouseEntered

    private void sign_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_bttnMouseExited
        // TODO add your handling code here:
        sign_bttn.setIcon(new ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\men_sign.png"));
    }//GEN-LAST:event_sign_bttnMouseExited

    private void log_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_bttnMouseEntered
        // TODO add your handling code here:
        log_bttn.setIcon(new ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\men_log_clicked.png"));
    }//GEN-LAST:event_log_bttnMouseEntered

    private void log_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_bttnMouseExited
        // TODO add your handling code here:
        log_bttn.setIcon(new ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\men_log.png"));
    }//GEN-LAST:event_log_bttnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel header1;
    private javax.swing.JLabel illustration;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton log_bttn;
    private javax.swing.JButton sign_bttn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
