/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package myproject.budget_app;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import myproject.Connect_DB.Menu_Assets;
/**
 *
 * @author jomsa
 */
public class Profile extends javax.swing.JDialog {

    /**
     * Creates new form Profile
     */
    public Profile(java.awt.Frame parent, boolean modal, int uid, String email) {
        super(parent, modal);
        setResizable(false);
        initComponents();
        this.email = email;
        Menu_Assets men = new Menu_Assets();
        String name = men.getFullName(uid);
        String username = men.getUserName(uid);
        
        id.setText(String.valueOf(uid));
        name_txt.setText(name);
        username_txt.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profile = new javax.swing.JLabel();
        name_txt = new javax.swing.JLabel();
        creator2 = new javax.swing.JLabel();
        user_lbl = new javax.swing.JLabel();
        username_txt = new javax.swing.JLabel();
        creators_lbl = new javax.swing.JLabel();
        id_lbl = new javax.swing.JLabel();
        denielle = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jom = new javax.swing.JLabel();
        creator1 = new javax.swing.JLabel();
        back_bttn = new javax.swing.JButton();
        log_out_bttn = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\profile_pic.png")); // NOI18N
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        name_txt.setFont(new java.awt.Font("Poppins Black", 1, 24)); // NOI18N
        name_txt.setText("NAMEEEEEE");
        getContentPane().add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 280, -1));

        creator2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        creator2.setText("Paz, Denielle Marie");
        getContentPane().add(creator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 120, 30));

        user_lbl.setFont(new java.awt.Font("Poppins Black", 0, 18)); // NOI18N
        user_lbl.setText("User name:");
        getContentPane().add(user_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, -1));

        username_txt.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        username_txt.setText("dfnjdsgn djgndng");
        getContentPane().add(username_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 160, 30));

        creators_lbl.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        creators_lbl.setText("Creators:");
        getContentPane().add(creators_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 70, 30));

        id_lbl.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        id_lbl.setText("id:");
        getContentPane().add(id_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 20, 30));

        denielle.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\denielle.png")); // NOI18N
        getContentPane().add(denielle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        id.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        id.setText("0000");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 40, 30));

        jom.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\jom_pic.png")); // NOI18N
        getContentPane().add(jom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        creator1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        creator1.setText("Tijada, Jomarie");
        getContentPane().add(creator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 100, 30));

        back_bttn.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\back_bttn.png")); // NOI18N
        back_bttn.setBorderPainted(false);
        back_bttn.setOpaque(false);
        back_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_bttnMouseExited(evt);
            }
        });
        back_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_bttnActionPerformed(evt);
            }
        });
        getContentPane().add(back_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, 40));

        log_out_bttn.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\log_out_bttn.png")); // NOI18N
        log_out_bttn.setBorderPainted(false);
        log_out_bttn.setOpaque(false);
        log_out_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                log_out_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                log_out_bttnMouseExited(evt);
            }
        });
        log_out_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_out_bttnActionPerformed(evt);
            }
        });
        getContentPane().add(log_out_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 110, 40));

        bg.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\bg9.jpg")); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void log_out_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_out_bttnMouseEntered
        // TODO add your handling code here:
        log_out_bttn.setIcon(new ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\log_out_bttn_clicked.png"));
    }//GEN-LAST:event_log_out_bttnMouseEntered

    private void log_out_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_out_bttnMouseExited
        // TODO add your handling code here:
        log_out_bttn.setIcon(new ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\log_out_bttn.png"));
    }//GEN-LAST:event_log_out_bttnMouseExited

    private void log_out_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_out_bttnActionPerformed
        // TODO add your handling code here:
        // Ask the user for confirmation before logging out
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", 
                                                    "Confirm Logout", JOptionPane.YES_NO_OPTION);

        // If user selects 'Yes', proceed with logging out
        if (response == JOptionPane.YES_OPTION) {
            // Close the current window (logout) and open the sign-in screen
            Sign_in sign = new Sign_in(this, true);
            this.dispose(); // Close the current window
            sign.setVisible(true); // Show the sign-in window
        }
    }//GEN-LAST:event_log_out_bttnActionPerformed

    private void back_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_bttnMouseEntered
        // TODO add your handling code here:
        back_bttn.setIcon(new ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\back_bttn_clicked.png"));
    }//GEN-LAST:event_back_bttnMouseEntered

    private void back_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_bttnMouseExited
        // TODO add your handling code here:
        back_bttn.setIcon(new ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\back_bttn.png"));
    }//GEN-LAST:event_back_bttnMouseExited

    private void back_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_bttnActionPerformed
        // TODO add your handling code here:
        Main men = new Main(email);
        this.dispose();
        men.setVisible(true);
    }//GEN-LAST:event_back_bttnActionPerformed

    /**
     * @param args the command line arguments
     */

    String email;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_bttn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel creator1;
    private javax.swing.JLabel creator2;
    private javax.swing.JLabel creators_lbl;
    private javax.swing.JLabel denielle;
    private javax.swing.JLabel id;
    private javax.swing.JLabel id_lbl;
    private javax.swing.JLabel jom;
    private javax.swing.JButton log_out_bttn;
    private javax.swing.JLabel name_txt;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel user_lbl;
    private javax.swing.JLabel username_txt;
    // End of variables declaration//GEN-END:variables
}
