/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package myproject.budget_app;

import javax.swing.*;
import myproject.Connect_DB.AMS;
/**
 *
 * @author jomsa
 */
public class Sign_in extends javax.swing.JDialog {

    /**
     * Creates new form Log_in
     */
    public Sign_in(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        
    }
    
    public Sign_in(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setResizable(false);
        initComponents();
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signBttn = new javax.swing.JButton();
        passTxt = new javax.swing.JPasswordField();
        haveAccLbl = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        logInTransBttn = new javax.swing.JButton();
        nameTxt = new javax.swing.JTextField();
        nameLbl = new javax.swing.JLabel();
        welcomeLbl1 = new javax.swing.JLabel();
        createAccNowLbl = new javax.swing.JLabel();
        email_lbl = new javax.swing.JLabel();
        passLbl = new javax.swing.JLabel();
        seePassChkBx = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signBttn.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\Sign_in.png")); // NOI18N
        signBttn.setBorderPainted(false);
        signBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signBttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signBttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signBttnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signBttnMouseReleased(evt);
            }
        });
        signBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signBttnActionPerformed(evt);
            }
        });
        getContentPane().add(signBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 120, 50));

        passTxt.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        passTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTxtActionPerformed(evt);
            }
        });
        getContentPane().add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 242, 300, 30));

        haveAccLbl.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        haveAccLbl.setForeground(new java.awt.Color(153, 153, 153));
        haveAccLbl.setText("Already have an account?");
        getContentPane().add(haveAccLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, 30));

        email_txt.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });
        getContentPane().add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 300, 30));

        logInTransBttn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        logInTransBttn.setForeground(new java.awt.Color(0, 153, 204));
        logInTransBttn.setText("Log in");
        logInTransBttn.setBorderPainted(false);
        logInTransBttn.setOpaque(false);
        logInTransBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInTransBttnActionPerformed(evt);
            }
        });
        getContentPane().add(logInTransBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 70, -1));

        nameTxt.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 300, 30));

        nameLbl.setBackground(new java.awt.Color(0, 0, 0));
        nameLbl.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        nameLbl.setText("Full Name:");
        getContentPane().add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 80, 30));

        welcomeLbl1.setFont(new java.awt.Font("Poppins Black", 1, 24)); // NOI18N
        welcomeLbl1.setText("Welcome");
        getContentPane().add(welcomeLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 130, 50));

        createAccNowLbl.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        createAccNowLbl.setForeground(new java.awt.Color(153, 153, 153));
        createAccNowLbl.setText("Create your account now");
        getContentPane().add(createAccNowLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 170, 30));

        email_lbl.setBackground(new java.awt.Color(0, 0, 0));
        email_lbl.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        email_lbl.setText("Email:");
        getContentPane().add(email_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 50, 30));

        passLbl.setBackground(new java.awt.Color(0, 0, 0));
        passLbl.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        passLbl.setText("Password:");
        getContentPane().add(passLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 80, 30));

        seePassChkBx.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        seePassChkBx.setForeground(new java.awt.Color(51, 51, 51));
        seePassChkBx.setText("See Password");
        seePassChkBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePassChkBxActionPerformed(evt);
            }
        });
        getContentPane().add(seePassChkBx, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\logInBg.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 620, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void seePassChkBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePassChkBxActionPerformed
        // TODO add your handling code here:
        // Toggle password visibility
        if (seePassChkBx.isSelected()) {
            passTxt.setEchoChar((char) 0); // Show password
        } else {
            passTxt.setEchoChar('*'); // Hide password
        }
    }//GEN-LAST:event_seePassChkBxActionPerformed

    private void signBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signBttnActionPerformed
        // TODO add your handling code here:
        // Gather input fields
        JTextField[] inputFields = {nameTxt, email_txt, passTxt};

        // Validate input and retrieve values
        String[] validatedInput = validateInput(inputFields);
        if (validatedInput == null) {
            return; // Exit if validation fails
        }

        // Extract validated input
        String name = validatedInput[0];
        String email = validatedInput[1];
        String password = validatedInput[2];

        // Attempt to sign up the user
        AMS signUpService = new AMS();
        boolean isSignUpSuccessful = signUpService.SignUp(name, email, password);

        if (isSignUpSuccessful) {
            // Proceed to the main application only if signup is successful
            Main mainMenu = new Main(name);
            this.dispose(); // Close the current dialog
            mainMenu.setVisible(true); // Show the main menu
        }                   
    }//GEN-LAST:event_signBttnActionPerformed

    private void passTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTxtActionPerformed

    private void logInTransBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInTransBttnActionPerformed
        // TODO add your handling code here:
        clear();
        Log_in log = new Log_in(this, true);
        this.dispose();
        log.setVisible(true);
    }//GEN-LAST:event_logInTransBttnActionPerformed

    private void signBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signBttnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_signBttnMouseClicked

    private void signBttnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signBttnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_signBttnMouseReleased

    private void signBttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signBttnMouseEntered
        // TODO add your handling code here:
        //change
        signBttn.setIcon(new ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\Sign_in_clicked.png"));
    }//GEN-LAST:event_signBttnMouseEntered

    private void signBttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signBttnMouseExited
        // TODO add your handling code here:
         signBttn.setIcon(new ImageIcon("D:\\[BSCS]\\Projects\\Info_Mgmt\\Budget_App\\budget_app\\image_assets\\Sign_in.png"));
    }//GEN-LAST:event_signBttnMouseExited

    private String[] validateInput(JTextField[] field) {
        String[] input = new String[field.length];
        for (int i = 0; i < field.length; i++) {
            String text = field[i].getText().trim();
            if (text.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill all the fields.");
                return null; // Validation failed
            }
            // Convert the first field to title case if necessary
            if (i == 0) {
                text = toTitleCase(text); // Assuming `toTitleCase` is a utility method
            }
            input[i] = text; // Assign text directly without concatenating
        }
        return input;
    }

    
    private void clear(){
        JTextField[] text = {nameTxt, email_txt, passTxt};
        for(int i = 0; i < text.length; i++){
            text[i].setText("");
        }
    }
    
    private String toTitleCase(String input) {
        if (input == null || input.isEmpty()) return input;
        String[] words = input.split(" ");
        StringBuilder titleCase = new StringBuilder();
        for (String word : words) {
            if (!word.isEmpty()) {
                titleCase.append(Character.toUpperCase(word.charAt(0)))
                        .append(word.substring(1).toLowerCase())
                        .append(" ");
            }
        }
        return titleCase.toString().trim();
    }

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createAccNowLbl;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JTextField email_txt;
    private javax.swing.JLabel haveAccLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logInTransBttn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel passLbl;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JCheckBox seePassChkBx;
    private javax.swing.JButton signBttn;
    private javax.swing.JLabel welcomeLbl1;
    // End of variables declaration//GEN-END:variables
}
